version: '2'
services:
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
    user: node
    volumes:
     - .:/var/www/html:cached
    networks:
     - vessel
networks:
  vessel:
    driver: "bridge"
